<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    function Test() {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          reject('error!') //reject 模拟出错
        }, 2000)
      })
    }
// 用try catch 捕捉错误
    // async function asyncTest() {
    //   try {
    //     console.log('start')
    //     await Test() // 这里返回了错误
    //     console.log('end') //这句不会执行
    //   } catch (err) {
    //     console.log(err)
    //   }
    // }

      // 不用try catch
    async function asyncTest() {

        console.log('start')
        await Test() // 这里返回了错误
        console.log('end') //这句不会执行
    }

    asyncTest().catch(function(err){
      console.log(err)
    })
  </script>
</body>

</html>